### PR TITLE
clnt_vc_ncreatf - Set error code in one failure case

### PR DESCRIPTION
**Pull request by dang**
Signed-off-by: Daniel Gryniewicz <dang@redhat.com>

### CODE REVIEW

**Review by mattbenjamin — APPROVED** [review]
the change looks correct, not verified for fixing the reported issue

**Comment by dang** [comment]
This is half the issue (the crash) which needs to be backported to 1.6.  The other half will be in another PR, that will need to be backported to 1.5 as well (and so should be separate from this PR)

**Comment by was4** [comment]
Thanks for correcting the oversight.  I'd removed it at some point to
stimulate a crash with that NULL, and apparently forgot to put it back.

However, that's the wrong error code, as the one you used requires an
errno.  Note that in clnt_dg.c I used

		clnt->cl_error.re_status = RPC_TLIERROR;

Of course in either case it means something very very bad has happened.

How was the crash reported, and what was the error log?

And why am I not seeing these crash reports?

**Comment by dang** [comment]
On 03/03/2018 04:25 AM, was4 wrote:
> Thanks for correcting the oversight. I'd removed it at some point to
> stimulate a crash with that NULL, and apparently forgot to put it back.
> 
> However, that's the wrong error code, as the one you used requires an
> errno. Note that in clnt_dg.c I used
> 
> clnt->cl_error.re_status = RPC_TLIERROR;
> 
> Of course in either case it means something very very bad has happened.

Okay, I guessed based on other errors in the surrounding code.

> 
> How was the crash reported, and what was the error log?

https://github.com/nfs-ganesha/nfs-ganesha/issues/270

> 
> And why am I not seeing these crash reports?

Are you subscribed to Ganesha issues on github?

Daniel

**Pull request merged**
