### PR TITLE
Casting a pointer to a non-varargs function to a pointer to a varargs function.

### PR DESCRIPTION
**Pull request by Safrout1**
Casting a pointer to a non-varargs function to a pointer to a varargs function.

### CODE REVIEW

**Comment by matvore** [comment]
Discussed this offline with Safrout1@ - this looks good to me - I requested my Signed-of-by line be added.

Just one more thing - to make this a bit cleaner, I recommend merging the two #if branches since _KERNEL is now the same as !_KERNEL.

**Comment by Safrout1** [comment]
> Discussed this offline with Safrout1@ - this looks good to me - I requested my Signed-of-by line be added.
> 
> Just one more thing - to make this a bit cleaner, I recommend merging the two #if branches since _KERNEL is now the same as !_KERNEL.

Done

**Review by dang — APPROVED** [review]

**Comment by ffilz** [comment]
Hmm, is there a Ganesha patch corresponding to this?

**Comment by dang** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/527048

**Comment by matvore** [comment]
> Hmm, is there a Ganesha patch corresponding to this?

Sorry for not realizing that this was a backwards-incompatible change. We are still excluding a lot of Ganesha components when building, so didn't notice. I'm going to start including PROXY_V3 FSAL in our CI to address this―FTR that was the motivation for https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/527066

**Comment by ffilz** [comment]
So I'm wondering if this is actually the right solution. Does anyone actually ever use the 3rd parameter? All of the Ganesha RPC procedure XDR functions just take two parameters but are cast to xdrproc_t and ultimately called with a 3rd parameter with a 0 value. Obviously that is safe for most? (all?) architectures since the caller manages the stack (or register parameters) and the fact that the function ignores them is not an issue and since the parameter is always zero (I hope...) there should be no architecture where there would be negative consequences for the xdr functions not saving a register (they won't touch an unused stack parameter but could use a register that was supposed to hold a caller's parameter). But if this is actually 0 all the time, maybe instead of adding the 3rd parameter where it's missing, we should just remove it in the few places it's used.

If there ARE places where the 3rd parameter to an xdrproc_t is NOT zero, we should understand those...

**Comment by matvore** [comment]
I could only find `0` as the last argument to `xdrproc_t` in libntirpc. My build, which excludes components, is successful with this patch: https://gist.github.com/matvore/572e4094b4f1acadada61e3616e7ef75

My guess is that this argument is either for encoding primitive values that fit in a word (decoding would have to use the pointer of course, if this is true) or for encode/decode flags.

I thought using an `unsigned int` for the third parameter was the right solution because (a) the _KERNEL branch of the `#ifdef` used it, and (b) Apple ran into exactly the same problem and used a prototype with `unsigned int` (see https://github.com/nfs-ganesha/ntirpc/issues/242)

Does ntirpc have any backwards-compatibility promises for clients besides NFS Ganesha? Maybe we can just delete this argument.

**Comment by ffilz** [comment]
Yea, I tried removing all the 3rd parameter and everything worked.

One thought I have is that 0 is to tell varargs there are no additional parameters.

None of the ntirpc or Ganesha XDR functions that are cast to xdrproc_t take a 3rd paramerer (and xdr_null actually takes NO parameters).

I have no idea if anything outside of Ganesha uses ntirpc, but there are enough API changes from plain old tirpc that ntirpc is NOT a drop in replacement for tirpc.

My vote is we remove this 3rd parameter and actually add 2 dummy parameters to xdr_null so that the only thing the function cast is doing is allowing the XDR functions to specify the type of the 2nd parameter (from void * to something specific) and not changing the number of parameters.

It SHOULD be the case that passing extra parameters is safe, on the other hand, if someone thought they could start passing a non-zero value that had meaning, they might be surprised.

Unfortunately I don't know if any compiler would complain about casting with different numbers of parameters.

Honestly I think it would have been better for all the XDR types to be explicit with a void * and cast to their own internal type inside the function.

**Comment by ffilz** [comment]
See https://github.com/nfs-ganesha/ntirpc/pull/246

**Pull request merged**
