### PR TITLE
add function rbtx_cleanup

### PR DESCRIPTION
**Pull request by xueqianhu47**
Currently we have rbtx_init, but not a corresponding clean up function. Add this rbtx_cleanup function to clean up resources allocated in the init part.

### CODE REVIEW

**Comment by xueqianhu47** [comment]
@ffilz please help review :-)

**Review by dang — APPROVED** [review]

**Comment by xueqianhu47** [comment]
Thanks @dang, can you also help merge this change

**Comment by dang** [comment]
> Thanks @dang, can you also help merge this change

Waiting for @ffilz review

**Review by ffilz — APPROVED** [review]
Looks good

**Comment by xueqianhu47** [comment]
@dang @ffilz thanks! can you help merge too :-)

**Pull request merged**
