### PR TITLE
Resolve Ganesha crash upon frequent connection open & close

### PR DESCRIPTION
**Pull request by rojingeorge**
This CR solves the race by connection close cleaning up svc_xprt and svc_rqst_clean_idle cleaning up svc_xprt

This resolves the findings of below issue
https://github.com/nfs-ganesha/ntirpc/issues/275

### CODE REVIEW

**Comment by Gaurav-Gangalwar** [comment]
@ffilz

**Comment by ffilz** [comment]
Looks good, @dang your thoughts?

**Comment by dang** [comment]
I don't like that svc_xprt_foreach() is now calling it's callback locked, but it's only used in one place, so I guess maybe it's okay?  Can you add a comment at the beginning of the function stating that the callback is called with the tree write locked?

**Comment by rojingeorge** [comment]
Sure @dang...Will update and push it in...

**Review by dang — APPROVED** [review]

**Pull request merged**
