### PR TITLE
WAS17 change clnt_req rbtree(s) to TAILQ

### PR DESCRIPTION
**Pull request by was4**

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@was4 I don't want this change

**Comment by was4** [comment]
Before:

Total: 989 samples
     321  32.5%  32.5%      321  32.5% svc_rqst_expire_cmpf
     149  15.1%  47.5%      475  48.0% opr_rbtree_insert
     139  14.1%  61.6%      140  14.2% __writev
      56   5.7%  67.2%       66   6.7% __GI___pthread_mutex_lock

**Comment by was4** [comment]
with xid list:

     311  25.7%  25.7%      311  25.7% svc_rqst_expire_cmpf
     275  22.7%  48.5%      372  30.8% clnt_req_process_reply
     143  11.8%  60.3%      454  37.6% opr_rbtree_insert
     114   9.4%  69.7%      115   9.5% __writev
      57   4.7%  74.4%       85   7.0% __GI___pthread_mutex_lock

**Comment by was4** [comment]
with expire list:

      81  27.0%  27.0%       81  27.0% __libc_recv
      29   9.7%  36.7%       29   9.7% __GI_epoll_pwait
      27   9.0%  45.7%       27   9.0% futex_abstimed_wait_cancelable
      20   6.7%  52.3%       20   6.7% futex_wake
      15   5.0%  57.3%       15   5.0% __writev
...
       3   1.0%  81.7%       12   4.0% clnt_req_process_reply

**Comment by mattbenjamin** [comment]
@was4 the problem is lack of relationship to available performance;  you're welcome to run it in your home server farm

**Pull request closed without merging**
