### PR TITLE
SVC IOQ - Dequeue the xioq before process

### PR DESCRIPTION
**Pull request by yangruifeng**
Signed-off-by: Yang Ruifeng <ruifeng@xsky.com>

### CODE REVIEW

**Review by dang — CHANGES_REQUESTED** [review]
So, this won't work, as-is, because if it gets EWOULDBLOCK, it needs to still be on the list.  Presumably, in this case, there was an error, and the xprt was destroyed?  In addition, we need to preserve the ordering, so we don't mix responses.    Would adding a TAILQ_REMOVE at line 351 before the SVC_DESTROY(), and a break after it fix the problem?

**Comment by yangruifeng** [comment]
@dang do you mean this？thanks

**Comment by dang** [comment]
Yep, that's exactly what I wanted.  Does this fix your issue?

**Comment by yangruifeng** [comment]
It takes a long time to test，i will reply tomorrow

**Comment by yangruifeng** [comment]
@dang this can not fix the issue

**Comment by yangruifeng** [comment]
maybe the function **svc_ioq_write** was called at the same time

**Comment by dang** [comment]
I don't think this should happen.  Only one write thread existst per xprt at a time, so that should be safe.  Read threads can call write, but svc_ioq_write_now() checks the write queue (under mutex), and if it's not empty, just queues, rather than calling svc_ioq_write().  Since svc_ioq_write() doesn't remove from the queue until it's done, there should be an entry on that queue whenever the mutex is not held.  So I think it's not possible for svc_ioq_write() to be called twice at the same time.

Do you see a callpath that could call svc_ioq_write() twice on the same xprt?

**Comment by yangruifeng** [comment]
@dang no.
can we use “have” after XDR_DESTROY(xioq->xdrs) ？

**Comment by yangruifeng** [comment]
**==138319== Invalid read of size 8**
==138319==    at 0x52AC920: svc_ioq_write (svc_ioq.c:393)
==138319==    by 0x52ACA8C: svc_ioq_write_now (svc_ioq.c:435)
==138319==    by 0x52A61B2: svc_vc_reply (svc_vc.c:964)
==138319==    by 0x529B7FC: svc_sendreply (svc.c:501)
==138319==    by 0x4E6628B: complete_request (nfs_worker_thread.c:764)
==138319==    by 0x4E68849: nfs_rpc_process_request (nfs_worker_thread.c:1513)
==138319==    by 0x4E68B49: nfs_rpc_valid_NFS (nfs_worker_thread.c:1617)
==138319==    by 0x52A5F48: svc_vc_decode (svc_vc.c:901)
==138319==    by 0x52A1E74: svc_request (svc_rqst.c:1201)
==138319==    by 0x52A5E59: svc_vc_recv (svc_vc.c:874)
==138319==    by 0x52A1DF5: svc_rqst_xprt_task_recv (svc_rqst.c:1182)
==138319==    by 0x52A2996: svc_rqst_epoll_loop (svc_rqst.c:1568)
**==138319==  Address 0x3ddec360 is 160 bytes inside a block of size 376 free'd**
==138319==    at 0x4C2AF9D: free (vg_replace_malloc.c:540)
==138319==    by 0x4E6C9AD: gsh_free_size (abstract_mem.h:272)
==138319==    by 0x52A8FE7: mem_free (types.h:214)
==138319==    by 0x52AA96A: xdr_ioq_destroy (xdr_ioq.c:782)
==138319==    by 0x52AA989: xdr_ioq_destroy_internal (xdr_ioq.c:789)
==138319==    by 0x52AC7F8: svc_ioq_write (svc_ioq.c:354)
==138319==    by 0x52ACA8C: svc_ioq_write_now (svc_ioq.c:435)
==138319==    by 0x52A61B2: svc_vc_reply (svc_vc.c:964)
==138319==    by 0x529B7FC: svc_sendreply (svc.c:501)
==138319==    by 0x4E6628B: complete_request (nfs_worker_thread.c:764)
==138319==    by 0x4E68849: nfs_rpc_process_request (nfs_worker_thread.c:1513)
==138319==    by 0x4E68B49: nfs_rpc_valid_NFS (nfs_worker_thread.c:1617)
**==138319==  Block was alloc'd at**
==138319==    at 0x4C2BFB9: calloc (vg_replace_malloc.c:762)
==138319==    by 0x4E6C8FC: gsh_calloc__ (abstract_mem.h:156)
==138319==    by 0x52A9A61: xdr_ioq_create (xdr_ioq.c:295)
==138319==    by 0x52A606E: svc_vc_reply (svc_vc.c:940)
==138319==    by 0x529B7FC: svc_sendreply (svc.c:501)
==138319==    by 0x4E6628B: complete_request (nfs_worker_thread.c:764)
==138319==    by 0x4E68849: nfs_rpc_process_request (nfs_worker_thread.c:1513)
==138319==    by 0x4E68B49: nfs_rpc_valid_NFS (nfs_worker_thread.c:1617)
==138319==    by 0x52A5F48: svc_vc_decode (svc_vc.c:901)
==138319==    by 0x52A1E74: svc_request (svc_rqst.c:1201)
==138319==    by 0x52A5E59: svc_vc_recv (svc_vc.c:874)
==138319==    by 0x52A1DF5: svc_rqst_xprt_task_recv (svc_rqst.c:1182)

**Review by dang — APPROVED** [review]
This looks okay to me.

**Comment by dang** [comment]
Asking for @ffilz to review as well

**Comment by ffilz** [comment]
Looks good to me.

**Review by ffilz — APPROVED** [review]

**Pull request merged**
