### PR TITLE
[xd |xprt] fix memory handling and refcounting.

### PR DESCRIPTION
**Pull request by sswen**
Signed-off-by: Swen Schillig swen@vnet.ibm.com

### CODE REVIEW

**Comment by sswen** [comment]
Any news on this one ?

**Comment by mattbenjamin** [comment]
@sswen still needs a test cycle, I'll sync up w/team

**Comment by mattbenjamin** [comment]
@sswen

**Comment by mattbenjamin** [comment]
@sswen reopen

**Comment by mattbenjamin** [comment]
@sswen ff

**Comment by mattbenjamin** [comment]
@sswen I can't seem to re-open this either;  if still applicable, can you rebase and re-send?  It may be possible to re-open if you use the same remote branch name, though I'm uncertain, as the source branch will have changed

**Pull request closed without merging**
