### PR TITLE
Cleanup extra ref after SVC_DESTROY.

### PR DESCRIPTION
**Pull request by Gaurav-Gangalwar**
We have extra ref taken on xprts that needs to be cleaned up post SVC_DESTROY.
Fix is to add cleanup handler for destroyed xprts svc_rqst_clean_destroyed.
svc_rqst_clean_idle is renamed to svc_rqst_destroy_idle, as its not actually
cleaning, its destroying the xprts, which will be cleaned up by svc_rqst_clean_idle.

### CODE REVIEW

**Comment by was4** [comment]
On 12/14/18 4:20 AM, Gaurav wrote:
> We have extra ref taken on xprts that needs to be cleaned up post SVC_DESTROY.
> Fix is to add cleanup handler for destroyed xprts svc_rqst_clean_destroyed.
> svc_rqst_clean_idle is renamed to svc_rqst_destroy_idle, as its not actually
> cleaning, its destroying the xprts, which will be cleaned up by svc_rqst_clean_idle.
> 
There is no "extra" ref.  Either you don't seem to understand the code logic, or
you don't seem to want to wait for the current process.  I've been trying to help,
but....

DanG and I have talked about this locally, and we agree that the 2013 design isn't
very good.  A better design would clean up one-a-time after an idle period of
(configurable) 5 minutes.  And that would require a sorted list, with re-insertions
every incoming message.  It has to be very very fast, so we'd probably use a TAILQ.

All of that is doable.  But not a high priority.  We don't have any reported
security problems where somebody is spamming the mounting and unmounting.  Just you.

We certainly don't want to run through the entire xprt list in the fast path.

**Comment by mattbenjamin** [comment]
@was4 please stop spreading misinformation about the "2013 design";  the refcounting is rebalanced by YOUR recent changes--not that it matters;  Next, there was, in the pre-recently logic no reliance on this list for cleanup of closed connections--it -was- the intent to close connection which...wait for it...had been IDLE for a long time, so that we could avoid holding open "too many" connections for an arbitrary period, and to perform other -not latency sensitive- per-transport cleanup work, such as cleaning up expired rpcsec_gss contexts, which otherwise also consume resources for an arbitrary period.    As noted elsewhere, we did have reliable detection of closed connections, and therefore of unmount events, such that there was no connection leak, without scanning this list.  It was unnecessary to identify therefore any connection in this list within a short window, and it was and would be again wasteful to perform xprt handle sorting on every request.  I very much agree with Guarav that it does matter if we leak connections on unmount.

**Comment by was4** [comment]
On 12/14/18 10:43 AM, Matt Benjamin wrote:
> @was4 <https://github.com/was4> please stop spreading misinformation about the "2013 design"; 

Matt,

Please stop spreading misinformation about the 2013 design of the idle
connection removal. I've not bothered to investigate which patch added
this wakeups code, because of the "Grand Reindent" of 2013. It was not
present in duplex-9 branch, and appears in duplex-10 branch.

It didn't actually work properly, as so much of the 2012-2014 era code
failed, because the author didn't use atomics across threads.

If you want to take credit for this indescribably poor code, you are
welcome to it.

It also timed-out the epoll loop every 120 seconds, an increase from 30
seconds in duplex-9 branch. I've reduced the timeouts to 29 seconds.

But it takes 1000 times the loop timeout to clean idle connections.
IMnsHO, a better design will clean up after only 5 minutes, and will be
configurable, and will not involve scanning the potentially tens of
thousands of transports for idle ones.

DanG and I have been trying to fix all the reference counting for years.
We've made good headway. Hopefully this is just one more instance.

**Comment by mattbenjamin** [comment]
@was4 I'm happy to take credit for this code and all of my work on ntirpc.  As regards this "indescribably poor code," the intent is to perform work that has no specific deadline--or, as would probably be a better improvement, out-of-line.  The specific intent was to avoid performing additional work with each incoming request--the fastest code is the code that never executes.  I'm happy to discuss this with you and Daniel at some convenient time.

**Pull request closed without merging**
