### PR TITLE
Fix use_after_free of xprt

### PR DESCRIPTION
**Pull request by soumyakoduri**
For any failures in svc_rqst_xprt_task()->svc_vc_recv(),
we mark xprt as destroyed and release the ref. Check for
its return status to avoid releasing the ref again.

Signed-off-by: Soumya Koduri <skoduri@redhat.com>

### CODE REVIEW

**Comment by mattbenjamin** [comment]
@soumyakoduri can you confirm where SVC_RELEASE will be called later, correctly, to release this call-path ref?

**Comment by dang** [comment]
There isn't a later SVC_RELEASE.  That's the issue, the xprt is released and destroyed immediately on the error, so you *can't* release it later.

**Review by dang — DISMISSED** [review]

**Comment by was4** [comment]
I've left a long answer on #153. This is probably the wrong fix. I cannot find the -1 in this new interface.

**Comment by mattbenjamin** [comment]
Not at all clear, in my opinion.  Happy to hear what model you favor, I'm in no way committed to not revising it.

**Review by mattbenjamin — COMMENTED** [review]
per call, I defer to you and daniel, I've added the context I can

**Comment by soumyakoduri** [comment]
https://github.com/nfs-ganesha/ntirpc/pull/155 rightly fixes this issue. Abandoning this change.

**Pull request closed without merging**
