### PR TITLE
authgss_hash: Fix race while initializing authgss_hash cache.

### PR DESCRIPTION
**Pull request by Gaurav-Gangalwar**
Signed-off-by: Gaurav Gangalwar <gaurav.gangalwar@gmail.com>

### CODE REVIEW

**Review by dang — COMMENTED** [review]
This is already protected.  authgss_hash_init() is only called via the cond_init_authgss_hash() macro, which checks that field already.

**Comment by Gaurav-Gangalwar** [comment]
> This is already protected. authgss_hash_init() is only called via the cond_init_authgss_hash() macro, which checks that field already.

I think just if check check is not enough, it should be protected with mutex in case of race.
If two threads end up calling cond_init_authgss_hash, then its possible that both of them will see authgss_hash_st.initialized == false, and end up in authgss_hash_init.
Why are we not protecting the initialised check with lock? we do similar in svc_xprt_init.

**Comment by dang** [comment]
Good point.  Probably this is a better solution: https://github.com/nfs-ganesha/ntirpc/pull/210

**Comment by Gaurav-Gangalwar** [comment]
> Good point. Probably this is a better solution: #210

Ok looks good. I will close this one then.

**Pull request closed without merging**
